#!/bin/bash
set -euo pipefail
mkdir -p out
clang -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-function -Isrc -o out/build src/build.c 
clang -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-function -Isrc -o out/main src/main.c   
clang -shared -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-function -Isrc -o out/main.so src/main.c   
