#!/bin/bash
set -euo pipefail
mkdir -p out
clang -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Isrc -o out/hot      app/hot.c
clang -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Isrc -o out/build    app/build.c
clang -g -O0 -Wall -Werror -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function -Isrc -o out/test     app/test.c

./out/test
./out/build "$@"
