#!/bin/bash
set -euo pipefail

FLAGS="-Wall -Werror \
       -Wno-unused-function \
       -Wno-unused-variable \
       -Wno-unused-but-set-variable \
       -std=c23 \
       -Ilib -Isrc \
       "

DEBUG="-g -O0"
RELEASE="-g0 -O2  -Xlinker --strip-all"

WINDOWS="-target x86_64-unknown-windows-gnu"

WASM="-target wasm32 \
      --no-standard-libraries \
      -Wl,--no-entry \
      -Wl,--export-all \
      -fno-builtin \
      -msimd128 \
      "

LINUX=""

mkdir -p out
set -x
clang $FLAGS $DEBUG $LINUX   -o out/snake src/snake.c
clang $FLAGS $DEBUG $WINDOWS -o out/snake.exe src/snake.c
clang $FLAGS $DEBUG $WASM    -o out/snake.wasm src/snake.c

# gcc   $FLAGS $DEBUG -o out/snake_gcc src/snake.c

