// Copyright (c) 2026 - Tom Smeets <tom@tsmeets.nl>
// ansi.h - ANSI Color codes for terminals
#pragma once
#define ANSI_RESET "\e[0m"
#define ANSI_BOLD "\e[1m"
#define ANSI_FAINT "\e[2m"
#define ANSI_UNDERLINE "\e[4m"
#define ANSI_BLINK "\e[5m"
#define ANSI_INVERT "\e[7m"
#define ANSI_STRIKE "\e[9m"
#define ANSI_BLACK "\e[30m"
#define ANSI_RED "\e[31m"
#define ANSI_GREEN "\e[32m"
#define ANSI_YELLOW "\e[33m"
#define ANSI_BLUE "\e[34m"
#define ANSI_MAGENTA "\e[35m"
#define ANSI_CYAN "\e[36m"
#define ANSI_WHITE "\e[37m"
#define ANSI_BLACK_BG "\e[40m"
#define ANSI_RED_BG "\e[41m"
#define ANSI_GREEN_BG "\e[42m"
#define ANSI_YELLOW_BG "\e[43m"
#define ANSI_BLUE_BG "\e[44m"
#define ANSI_MAGENTA_BG "\e[45m"
#define ANSI_CYAN_BG "\e[46m"
#define ANSI_WHITE_BG "\e[47m"
